# Davinci CLI Test
on: [push, pull_request]
name: Davinci CLI Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
      with:
        go-version: ${{ matrix.go-version }}
    - run: |
           go install
           echo "Hello World" > ./before.txt
           go run main.go new-passphrase --folder ./
           go run main.go new-keypair --size 2048 --passphrase ./passphrase.txt --folder ./
           go run main.go key --folder ./
           go run main.go encrypt --input ./before.txt --output ./secret.txt --key ./key.txt --passphrase ./passphrase.txt --public-key ./publicKey.pem
           go run main.go decrypt --input ./secret.txt --output ./after.txt --passphrase ./passphrase.txt --private-key ./privateKey.pem
           export BEFORE_CONTENT=$(cat ./before.txt)
           export AFTER_CONTENT=$(cat ./after.txt)
           cmp --silent $BEFORE_CONTENT $AFTER_CONTENT || echo "files are different"


           