name: "DaVinci Development Pipeline"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Verify dependencies
        run: go mod verify

      - name: Install
        run: go install

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

  lint:
    - name: Verify dependencies
      run: go mod verify

    - name: Install
      run: go install

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./...

  test:
    - name: Verify dependencies
      run: go mod verify

    - name: Install
      run: go install

    - name: Run tests
      run: go test -race -vet=off ./...
